config/routes.rb
Rails.application.routes.draw do
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepotTdd</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name %>">
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Listing Products</h1>

<table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"
      id="<%= product.id %>">

      <td>
        <%= image_tag product.image_url, class: 'list_image', width: 60, height: 70 %>
      </td>

      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description),
            length: 80) %></dd>
        </dl>
      </td>

      <td class="list_actions">
        <%= link_to 'Show', product %><br/>
        <%# link_to 'Edit', edit_product_path(product) %><br/>
        <%# link_to 'Destroy', product, method: :delete,
          data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New product', new_product_path %>